import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import providersRouter from "./providers.js";
import aiConfigRouter from "./aiConfig.js";
import productsRouter from "./products.js";
import ordersRouter from "./orders.js";
import conversationsRouter from "./conversations.js";
import commentsRouter from "./comments.js";
import fbSettingsRouter from "./fbSettings.js";
import webhookRouter from "./webhook.js";
import statsRouter from "./stats.js";
import appointmentsRouter from "./appointments.js";
import slotsRouter from "./slots.js";
import faqsRouter from "./faqs.js";
import broadcastsRouter from "./broadcasts.js";
import leadsRouter from "./leads.js";
import domainTemplatesRouter from "./domainTemplates.js";
import notificationsRouter from "./notifications.js";
import reliabilityRouter from "./reliability.js";
import conversionsRouter from "./conversions.js";
import { preOrdersRouter } from "./preOrders.js";
import deliveryPricesRouter from "./deliveryPrices.js";
import productCategoriesRouter from "./productCategories.js";
import productFoldersRouter from "./productFolders.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(notificationsRouter);
router.use(providersRouter);
router.use(aiConfigRouter);
router.use(productsRouter);
router.use(ordersRouter);
router.use(conversationsRouter);
router.use(commentsRouter);
router.use(fbSettingsRouter);
router.use(webhookRouter);
router.use(statsRouter);
router.use(appointmentsRouter);
router.use(slotsRouter);
router.use(faqsRouter);
router.use(broadcastsRouter);
router.use(leadsRouter);
router.use(domainTemplatesRouter);
router.use(reliabilityRouter);
router.use(conversionsRouter);
router.use("/pre-orders", preOrdersRouter);
router.use(deliveryPricesRouter);
router.use(productCategoriesRouter);
router.use(productFoldersRouter);

export default router;
