import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import providersRouter from "./providers";
import aiConfigRouter from "./aiConfig";
import productsRouter from "./products";
import ordersRouter from "./orders";
import conversationsRouter from "./conversations";
import commentsRouter from "./comments";
import fbSettingsRouter from "./fbSettings";
import webhookRouter from "./webhook";
import statsRouter from "./stats";
import appointmentsRouter from "./appointments";
import slotsRouter from "./slots";
import faqsRouter from "./faqs";
import broadcastsRouter from "./broadcasts";
import leadsRouter from "./leads";
import domainTemplatesRouter from "./domainTemplates";
import notificationsRouter from "./notifications";
import reliabilityRouter from "./reliability";
import conversionsRouter from "./conversions";
import { preOrdersRouter } from "./preOrders";
import deliveryPricesRouter from "./deliveryPrices";
import productCategoriesRouter from "./productCategories";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(notificationsRouter);
router.use(providersRouter);
router.use(aiConfigRouter);
router.use(productsRouter);
router.use(ordersRouter);
router.use(conversationsRouter);
router.use(commentsRouter);
router.use(fbSettingsRouter);
router.use(webhookRouter);
router.use(statsRouter);
router.use(appointmentsRouter);
router.use(slotsRouter);
router.use(faqsRouter);
router.use(broadcastsRouter);
router.use(leadsRouter);
router.use(domainTemplatesRouter);
router.use(reliabilityRouter);
router.use(conversionsRouter);
router.use("/pre-orders", preOrdersRouter);
router.use(deliveryPricesRouter);
router.use(productCategoriesRouter);

export default router;
