import { pgTable, serial, text, integer, timestamp } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

export const aiConfigTable = pgTable("ai_config", {
  id: serial("id").primaryKey(),
  botName: text("bot_name").notNull().default("مساعد المتجر"),
  personality: text("personality"),
  greetingMessage: text("greeting_message"),
  language: text("language").notNull().default("auto"),
  respondToOrders: integer("respond_to_orders").notNull().default(1),
  replyToComments: integer("reply_to_comments").notNull().default(1),
  sendDmOnComment: integer("send_dm_on_comment").notNull().default(1),
  activeProviderId: integer("active_provider_id"),
  businessCountry: text("business_country"),
  businessCity: text("business_city"),
  businessDomain: text("business_domain"),
  businessDomainCustom: text("business_domain_custom"),
  targetAudience: text("target_audience"),
  businessHoursStart: text("business_hours_start").default("09:00"),
  businessHoursEnd: text("business_hours_end").default("22:00"),
  timezone: text("timezone").notNull().default("Africa/Algiers"),
  outsideHoursMessage: text("outside_hours_message"),
  currency: text("currency").notNull().default("DZD"),
  pageName: text("page_name"),
  pageDescription: text("page_description"),
  pageLogoUrl: text("page_logo_url"),
  pageFacebookUrl: text("page_facebook_url"),
  strictTopicMode: integer("strict_topic_mode").notNull().default(0),
  offTopicResponse: text("off_topic_response"),
  blockedKeywords: text("blocked_keywords"),
  maxOffTopicMessages: integer("max_off_topic_messages").notNull().default(3),
  handoffKeyword: text("handoff_keyword").default("بشري"),
  handoffMessage: text("handoff_message").default("تم تحويلك إلى فريق الدعم البشري. سيتواصل معك أحد ممثلينا قريباً."),
  currentPlan: text("current_plan").notNull().default("free"),
  leadCaptureEnabled: integer("lead_capture_enabled").notNull().default(0),
  leadCaptureFields: text("lead_capture_fields").notNull().default('["phone"]'),
  leadCaptureMessage: text("lead_capture_message").default("يسعدنا خدمتك! هل يمكنك مشاركتنا رقم هاتفك للتواصل؟"),
  useQuickReplies: integer("use_quick_replies").notNull().default(1),
  quickReplyButtons: text("quick_reply_buttons"),
  workingHoursEnabled: integer("working_hours_enabled").notNull().default(1),
  abandonedCartEnabled: integer("abandoned_cart_enabled").notNull().default(1),
  abandonedCartDelayHours: integer("abandoned_cart_delay_hours").notNull().default(1),
  abandonedCartMessage: text("abandoned_cart_message").default("مرحباً! 👋 لاحظنا اهتمامك بـ {product_name}\nهل تريد إتمام طلبك؟ نحن هنا لمساعدتك 😊"),
  botEnabled: integer("bot_enabled").notNull().default(1),
  botDisabledMessage: text("bot_disabled_message").default("عذراً، المساعد الذكي غير متاح حالياً. يرجى التواصل معنا لاحقاً."),
  confidenceThreshold: text("confidence_threshold").notNull().default("0.5"),
  confidenceBelowAction: text("confidence_below_action").notNull().default("none"),
  safeModeEnabled: integer("safe_mode_enabled").notNull().default(0),
  safeModeLevel: text("safe_mode_level").notNull().default("standard"),
  customerMemoryEnabled: integer("customer_memory_enabled").notNull().default(0),
  salesBoostEnabled: integer("sales_boost_enabled").notNull().default(0),
  salesBoostLevel: text("sales_boost_level").notNull().default("medium"),
  priceLockEnabled: integer("price_lock_enabled").notNull().default(0),
  humanGuaranteeEnabled: integer("human_guarantee_enabled").notNull().default(0),
  smartEscalationEnabled: integer("smart_escalation_enabled").notNull().default(0),
  deliveryEnabled: integer("delivery_enabled").notNull().default(0),
  appointmentsEnabled: integer("appointments_enabled").notNull().default(0),
  updatedAt: timestamp("updated_at", { withTimezone: true }),
});

export const insertAiConfigSchema = createInsertSchema(aiConfigTable).omit({ id: true });
export type InsertAiConfig = z.infer<typeof insertAiConfigSchema>;
export type AiConfig = typeof aiConfigTable.$inferSelect;
